version: '3'
services: 
    web-app: 
        environment:
            - CHOKIDAR_USEPOLLING=true
        #Hack, otherwise the npm server will be closed 
        stdin_open: true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules
            #Mapping host fs to container 
            - .:/app
    tests: 
        environment:
            - CHOKIDAR_USEPOLLING=true
        #Hack, otherwise the npm server will be closed 
        stdin_open: true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            #Mapping host fs to container 
            - .:/app
        command: ["npm", "run", "test"]