FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install 

COPY . . 

CMD [ "npm", "run", "start" ]

# docker run -it -p 3000:3000 CONTAINER_ID
#docker run -it -p 3000:3000 -v /app/node_modules -v ${pwd}:/app -e CHOKIDAR_USEPOLLING=true CONTAINER_ID
#  web: 
#    stdin_open: true